### ISSUE TITLE
More flexible Entities Card

### ISSUE THREAD

**Issue by rgruebel** [custom-cards/information#10]
I have a custom_component in which I load the waste dates for my district. At the moment it is not possible for me to sort them in Lovelace by the date of the next collection. I also need to create a template sensor for each entity just to display an attribute in the Entities Card.

I'd like to have a more flexible Entities Card where I can decide whether to display the actual value of an entity or a specific attribute. Also it must be possible to sort the entities either by an attribute or by the actual value but independent of the value displayed in the card. Wildcards for Entities would also be very usefull for this card (like the monster card).

I think we still need to think about different datatypes or if not all contained entities have the given attribute.
![alt text](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/c/b/cb08981e4d1812e75022c626695c1b2fb91f76ce.png "entity")

![alt text](https://community-home-assistant-assets.s3.dualstack.us-west-2.amazonaws.com/original/3X/b/9/b9739c49aa314318d1fd49d1cb799fcec9db2363.png "card")

**Comment by rdehuyss** [comment]
+1

**Comment by kaosmagix** [comment]
+1. Can this request be re-opened? (I want to have this for exactly the same reason (garbage collection days)

**Comment by esenterre** [comment]
Exact same thing here too. I think we are better serve by ourself in this case.
Maybe a good opportunity to learn the back-end of HA... I'll see.

**Comment by bregtvandenbergh** [comment]
+1 me too

**Comment by ThirstyThursten** [comment]
4 years late to this party, but I would like to have this as well! :P
