### ISSUE TITLE
Timer Card

### ISSUE THREAD

**Issue by mynameisdaniel32** [custom-cards/information#12]
**Is your feature request related to a problem? Please describe.**
It'd be nice in the front end to be able to see a live countdown timer for timer entities when they're active. 

**Describe the solution you'd like**
A simple timer card which shows the remainining time when the timer is active as a countdown, with optional buttons to control the timer (i.e. start, stop, pause, etc.). When the timer isn't active, it should show the configured/default time.

**Describe alternatives you've considered**
Currently I'm doing this with a sensor which updates every second, but it's very messy and would be even messier for me to add controls.

**Comment by iantrich** [comment]
@mynameisdaniel32 so I got around to doing something for this, but the design is crap

![image](https://user-images.githubusercontent.com/1287159/56175603-7e10d200-5fbd-11e9-93ac-1225fb5753e8.png)

Did you have anything in mind for how you wanted this to look?

**Comment by iantrich** [comment]
https://github.com/custom-cards/timer-card

**Comment by iantrich** [comment]
An option to have your own timer, an not an entity and fire a service at the end could be nice as well. You could then set it to whatever you want and could also do a stopwatch function. Not being tied to an entity, means it would only be relevant to that one particular session as it wouldn't be part of the state-machine. Perhaps using an input-date-time would be a better approach.
