### ISSUE TITLE
Org Icon suggestion

### ISSUE THREAD

**Issue by Gluwc** [custom-cards/information#14]
**Is your feature request related to a problem? Please describe.**
The problem is this org not having a nice icon.

**Describe the solution you'd like**
Use attached custom icon.

**Describe alternatives you've considered**
Be disappointed by the default github icon.

![custom-cards](https://user-images.githubusercontent.com/38736396/55487170-dba43680-562d-11e9-950c-9bfb31f525ea.png)

**Comment by iantrich** [comment]
Cool
![image](https://user-images.githubusercontent.com/1287159/55487530-e5a94380-55f3-11e9-91f5-f4ea4ad5400d.png)
