### ISSUE TITLE
Add mini-media-player in repos.json

### ISSUE THREAD

**Issue by gerard33** [custom-cards/information#3]
Is it possible to add [mini-media-player](https://github.com/kalkih/mini-media-player) in repos.json?

The [tracker.json](https://github.com/kalkih/mini-media-player/blob/master/tracker.json) is available on the repo and that way we don't need to follow this [instruction](https://github.com/kalkih/mini-media-player#optional-add-to-custom-updater) but it gets automatically part of the tracker card isn't it?

At least the repo https://github.com/thomasloven seems to work like that :grey_question: 

CC @kalkih

**Comment by ludeeus** [comment]
@gerard33 That json file are generated with this script that runs every 10 min
<https://github.com/ludeeus/custom_updater_CI/blob/master/scripts/json_cards.sh>
PR's are welcome :)
