### ISSUE TITLE
FR - Better Light Card

### ISSUE THREAD

**Issue by daphatty** [custom-cards/information#9]
Any chance you could make a better version of the default Light Card?

**Comment by iantrich** [comment]
quite a broad request and I don't like the idea of duplicating core if not necessary. likely the better path would be to enhance the core card once the feature freeze is over ~0.87

**Comment by daphatty** [comment]
I didn't want to be presumptuous by suggesting edits to the core version. Plus, with a few exceptions, Lovelace Core features pale in comparison to what the community has released. Thanks for the reply though.

**Comment by iantrich** [comment]
a light is core, add feature requests to core cards are completely acceptable: https://github.com/home-assistant/ui-schema/issues
